// Code generated by goctl. DO NOT EDIT!

package trademodel

import (
	"context"
	"database/sql"
	"strings"
	"time"

	"github.com/klen-ygs/gorm-zero/gormc"
	. "github.com/klen-ygs/gorm-zero/gormc/sql"
	"gorm.io/gorm"
	"github.com/shopspring/decimal"
)

// avoid unused err
var _ = time.Second

type (
	tradeOrderLogModel interface {
		Insert(ctx context.Context, data *TradeOrderLog) error

		FindOne(ctx context.Context, id int64) (*TradeOrderLog, error)
		FindOneByOrderIdStatus(ctx context.Context, orderId int64, status int64) (*TradeOrderLog, error)
		Update(ctx context.Context, data *TradeOrderLog) error

		Delete(ctx context.Context, id int64) error
	}

	defaultTradeOrderLogModel struct {
		conn  *gorm.DB
		table string
	}

	TradeOrderLog struct {
		Id              int64     `gorm:"column:id"`
		OrderId         int64     `gorm:"column:order_id"`
		Uid             int64     `gorm:"column:uid"`
		TradeType       int64     `gorm:"column:trade_type"` // 1:market 2：limit
		ChainId         int64     `gorm:"column:chain_id"`
		TokenCa         string    `gorm:"column:token_ca"`
		SwapType        int64     `gorm:"column:swap_type"` // 1:buy 2:sell
		WalletIndex     int64     `gorm:"column:wallet_index"`
		WalletAddress   string    `gorm:"column:wallet_address"`
		IsAutoSlippage  int64     `gorm:"column:is_auto_slippage"`
		Slippage        int64     `gorm:"column:slippage"`
		IsAntiMev       int64     `gorm:"column:is_anti_mev"`
		GasType         int64     `gorm:"column:gas_type"` // 手续费类型 1 normal 2：fast 3：superspeed
		Status          int64     `gorm:"column:status"`   // 1：wait 2:proc 3:onchain 4:fail 5:suc 6:cancel 7:timeout fail
		FailReason      string    `gorm:"column:fail_reason"`
		DoubleOut       int64     `gorm:"column:double_out"`       // 是否翻倍出本 1:是 0:否
		OrderCap        decimal.Decimal `gorm:"column:order_cap"`        // 挂单市值 token的流动性市值
		OrderAmount     decimal.Decimal `gorm:"column:order_amount"`     // 挂单数量（付出的币种 买:base 卖:token）
		OrderPriceBase  decimal.Decimal `gorm:"column:order_price_base"` // 挂单价格 token对base的价格
		OrderValueBase  decimal.Decimal `gorm:"column:order_value_base"` // 挂单总价 （base）买： 挂单数量   卖：挂单数量*挂单总价
		OrderBasePrice  decimal.Decimal `gorm:"column:order_base_price"` // base to usd
		FinalCap        decimal.Decimal `gorm:"column:final_cap"`        // 最终市值 token的流动性市值
		FinalAmount     decimal.Decimal `gorm:"column:final_amount"`     // 最终数量（得到的币种 买:token 卖:base）
		FinalPriceBase  decimal.Decimal `gorm:"column:final_price_base"` // 最终价格 token对base的价格
		FinalValueBase  decimal.Decimal `gorm:"column:final_value_base"` // 最终总价值（base）买：最终数量 * 最终价格   卖：最终数量
		FinalBasePrice  decimal.Decimal `gorm:"column:final_base_price"` // base to usd
		GasFee          decimal.Decimal `gorm:"column:gas_fee"`          // sol
		PriorityFee     decimal.Decimal `gorm:"column:priority_fee"`     // sol
		DexFee          decimal.Decimal `gorm:"column:dex_fee"`          // intoken
		ServerFee       decimal.Decimal `gorm:"column:server_fee"`       // sol
		JitoFee         decimal.Decimal `gorm:"column:jito_fee"`         // sol
		TxHash          string    `gorm:"column:tx_hash"`
		DexName         string    `gorm:"column:dex_name"` // 交易时选取的交易所
		PairCa          string    `gorm:"column:pair_ca"`  // 交易时选取的交易池
		CreatedAt       time.Time `gorm:"column:created_at"`
		DrawdownPrice   decimal.Decimal `gorm:"column:drawdown_price"`   // 回撤触发价格
		TrailingPercent int64     `gorm:"column:trailing_percent"` // 回撤百分比
	}
)

var QTradeOrderLog TradeOrderLog

func init() {
	InitField(&QTradeOrderLog)
}

func (TradeOrderLog) TableName() string {
	return strings.Trim("`trade_order_log`", "`")
}

func newTradeOrderLogModel(conn *gorm.DB) *defaultTradeOrderLogModel {
	return &defaultTradeOrderLogModel{
		conn:  conn,
		table: strings.Trim("`trade_order_log`", "`"),
	}
}

func (m *defaultTradeOrderLogModel) Insert(ctx context.Context, data *TradeOrderLog) error {
	db := m.conn
	err := db.WithContext(ctx).Save(&data).Error
	return err
}

func (m *defaultTradeOrderLogModel) FindOne(ctx context.Context, id int64) (*TradeOrderLog, error) {
	var resp TradeOrderLog
	err := m.conn.WithContext(ctx).Model(&TradeOrderLog{}).Where("`id` = @id", sql.Named("id", id)).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err

}

func (m *defaultTradeOrderLogModel) FindOneByOrderIdStatus(ctx context.Context, orderId int64, status int64) (*TradeOrderLog, error) {
	var resp TradeOrderLog
	err := m.conn.WithContext(ctx).Model(&TradeOrderLog{}).Where("`order_id` = ? and `status` = ?", orderId, status).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err
}

func (m *defaultTradeOrderLogModel) Update(ctx context.Context, data *TradeOrderLog) error {
	db := m.conn
	err := db.WithContext(ctx).Save(data).Error
	return err
}

func (m *defaultTradeOrderLogModel) Delete(ctx context.Context, id int64) error {
	db := m.conn
	err := db.WithContext(ctx).Where("`id` = @id", sql.Named("id", id)).Delete(&TradeOrderLog{}).Error

	return err
}
