// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: dataflow.proto

package dataflow

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Klines struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Kline               `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Klines) Reset() {
	*x = Klines{}
	mi := &file_dataflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Klines) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Klines) ProtoMessage() {}

func (x *Klines) ProtoReflect() protoreflect.Message {
	mi := &file_dataflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Klines.ProtoReflect.Descriptor instead.
func (*Klines) Descriptor() ([]byte, []int) {
	return file_dataflow_proto_rawDescGZIP(), []int{0}
}

func (x *Klines) GetList() []*Kline {
	if x != nil {
		return x.List
	}
	return nil
}

type Kline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       int64                  `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Interval      string                 `protobuf:"bytes,2,opt,name=interval,proto3" json:"interval,omitempty"`
	PairAddr      string                 `protobuf:"bytes,3,opt,name=pair_addr,json=pairAddr,proto3" json:"pair_addr,omitempty"`
	Open          float64                `protobuf:"fixed64,4,opt,name=open,proto3" json:"open,omitempty"`
	High          float64                `protobuf:"fixed64,5,opt,name=high,proto3" json:"high,omitempty"`
	Low           float64                `protobuf:"fixed64,6,opt,name=low,proto3" json:"low,omitempty"`
	Close         float64                `protobuf:"fixed64,7,opt,name=close,proto3" json:"close,omitempty"`
	McapOpen      float64                `protobuf:"fixed64,8,opt,name=mcap_open,json=mcapOpen,proto3" json:"mcap_open,omitempty"`
	McapHigh      float64                `protobuf:"fixed64,9,opt,name=mcap_high,json=mcapHigh,proto3" json:"mcap_high,omitempty"`
	McapLow       float64                `protobuf:"fixed64,10,opt,name=mcap_low,json=mcapLow,proto3" json:"mcap_low,omitempty"`
	McapClose     float64                `protobuf:"fixed64,11,opt,name=mcap_close,json=mcapClose,proto3" json:"mcap_close,omitempty"`
	AmountUsd     float64                `protobuf:"fixed64,12,opt,name=amount_usd,json=amountUsd,proto3" json:"amount_usd,omitempty"`
	VolumeToken   float64                `protobuf:"fixed64,13,opt,name=volume_token,json=volumeToken,proto3" json:"volume_token,omitempty"`
	CandleTime    int64                  `protobuf:"varint,14,opt,name=candle_time,json=candleTime,proto3" json:"candle_time,omitempty"`
	BuyCount      int64                  `protobuf:"varint,15,opt,name=buy_count,json=buyCount,proto3" json:"buy_count,omitempty"`
	SellCount     int64                  `protobuf:"varint,16,opt,name=sell_count,json=sellCount,proto3" json:"sell_count,omitempty"`
	TotalCount    int64                  `protobuf:"varint,17,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	CloseAt       int64                  `protobuf:"varint,18,opt,name=close_at,json=closeAt,proto3" json:"close_at,omitempty"`
	OpenAt        int64                  `protobuf:"varint,19,opt,name=open_at,json=openAt,proto3" json:"open_at,omitempty"`
	AvgPrice      float64                `protobuf:"fixed64,20,opt,name=avg_price,json=avgPrice,proto3" json:"avg_price,omitempty"`
	MktCap        float64                `protobuf:"fixed64,21,opt,name=mkt_cap,json=mktCap,proto3" json:"mkt_cap,omitempty"`
	PumpPoint     float64                `protobuf:"fixed64,22,opt,name=pump_point,json=pumpPoint,proto3" json:"pump_point,omitempty"`
	TokenAddr     string                 `protobuf:"bytes,23,opt,name=token_addr,json=tokenAddr,proto3" json:"token_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kline) Reset() {
	*x = Kline{}
	mi := &file_dataflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kline) ProtoMessage() {}

func (x *Kline) ProtoReflect() protoreflect.Message {
	mi := &file_dataflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kline.ProtoReflect.Descriptor instead.
func (*Kline) Descriptor() ([]byte, []int) {
	return file_dataflow_proto_rawDescGZIP(), []int{1}
}

func (x *Kline) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *Kline) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *Kline) GetPairAddr() string {
	if x != nil {
		return x.PairAddr
	}
	return ""
}

func (x *Kline) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *Kline) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *Kline) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Kline) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *Kline) GetMcapOpen() float64 {
	if x != nil {
		return x.McapOpen
	}
	return 0
}

func (x *Kline) GetMcapHigh() float64 {
	if x != nil {
		return x.McapHigh
	}
	return 0
}

func (x *Kline) GetMcapLow() float64 {
	if x != nil {
		return x.McapLow
	}
	return 0
}

func (x *Kline) GetMcapClose() float64 {
	if x != nil {
		return x.McapClose
	}
	return 0
}

func (x *Kline) GetAmountUsd() float64 {
	if x != nil {
		return x.AmountUsd
	}
	return 0
}

func (x *Kline) GetVolumeToken() float64 {
	if x != nil {
		return x.VolumeToken
	}
	return 0
}

func (x *Kline) GetCandleTime() int64 {
	if x != nil {
		return x.CandleTime
	}
	return 0
}

func (x *Kline) GetBuyCount() int64 {
	if x != nil {
		return x.BuyCount
	}
	return 0
}

func (x *Kline) GetSellCount() int64 {
	if x != nil {
		return x.SellCount
	}
	return 0
}

func (x *Kline) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *Kline) GetCloseAt() int64 {
	if x != nil {
		return x.CloseAt
	}
	return 0
}

func (x *Kline) GetOpenAt() int64 {
	if x != nil {
		return x.OpenAt
	}
	return 0
}

func (x *Kline) GetAvgPrice() float64 {
	if x != nil {
		return x.AvgPrice
	}
	return 0
}

func (x *Kline) GetMktCap() float64 {
	if x != nil {
		return x.MktCap
	}
	return 0
}

func (x *Kline) GetPumpPoint() float64 {
	if x != nil {
		return x.PumpPoint
	}
	return 0
}

func (x *Kline) GetTokenAddr() string {
	if x != nil {
		return x.TokenAddr
	}
	return ""
}

type Kline24InfoItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Change_24     float64                `protobuf:"fixed64,1,opt,name=change_24,json=change24,proto3" json:"change_24,omitempty"`
	Txs_24H       uint32                 `protobuf:"varint,2,opt,name=txs_24h,json=txs24h,proto3" json:"txs_24h,omitempty"`
	Vol_24H       float64                `protobuf:"fixed64,3,opt,name=vol_24h,json=vol24h,proto3" json:"vol_24h,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kline24InfoItem) Reset() {
	*x = Kline24InfoItem{}
	mi := &file_dataflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kline24InfoItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kline24InfoItem) ProtoMessage() {}

func (x *Kline24InfoItem) ProtoReflect() protoreflect.Message {
	mi := &file_dataflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kline24InfoItem.ProtoReflect.Descriptor instead.
func (*Kline24InfoItem) Descriptor() ([]byte, []int) {
	return file_dataflow_proto_rawDescGZIP(), []int{2}
}

func (x *Kline24InfoItem) GetChange_24() float64 {
	if x != nil {
		return x.Change_24
	}
	return 0
}

func (x *Kline24InfoItem) GetTxs_24H() uint32 {
	if x != nil {
		return x.Txs_24H
	}
	return 0
}

func (x *Kline24InfoItem) GetVol_24H() float64 {
	if x != nil {
		return x.Vol_24H
	}
	return 0
}

type KlineFluctuation struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	KlineFluctuation_1M  float64                `protobuf:"fixed64,1,opt,name=kline_fluctuation_1m,json=klineFluctuation1m,proto3" json:"kline_fluctuation_1m,omitempty"`
	KlineFluctuation_5M  float64                `protobuf:"fixed64,2,opt,name=kline_fluctuation_5m,json=klineFluctuation5m,proto3" json:"kline_fluctuation_5m,omitempty"`
	KlineFluctuation_15M float64                `protobuf:"fixed64,3,opt,name=kline_fluctuation_15m,json=klineFluctuation15m,proto3" json:"kline_fluctuation_15m,omitempty"`
	KlineFluctuation_1H  float64                `protobuf:"fixed64,4,opt,name=kline_fluctuation_1h,json=klineFluctuation1h,proto3" json:"kline_fluctuation_1h,omitempty"`
	KlineFluctuation_4H  float64                `protobuf:"fixed64,5,opt,name=kline_fluctuation_4h,json=klineFluctuation4h,proto3" json:"kline_fluctuation_4h,omitempty"`
	KlineFluctuation_12H float64                `protobuf:"fixed64,6,opt,name=kline_fluctuation_12h,json=klineFluctuation12h,proto3" json:"kline_fluctuation_12h,omitempty"`
	KlineFluctuation_24H float64                `protobuf:"fixed64,7,opt,name=kline_fluctuation_24h,json=klineFluctuation24h,proto3" json:"kline_fluctuation_24h,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *KlineFluctuation) Reset() {
	*x = KlineFluctuation{}
	mi := &file_dataflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KlineFluctuation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KlineFluctuation) ProtoMessage() {}

func (x *KlineFluctuation) ProtoReflect() protoreflect.Message {
	mi := &file_dataflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KlineFluctuation.ProtoReflect.Descriptor instead.
func (*KlineFluctuation) Descriptor() ([]byte, []int) {
	return file_dataflow_proto_rawDescGZIP(), []int{3}
}

func (x *KlineFluctuation) GetKlineFluctuation_1M() float64 {
	if x != nil {
		return x.KlineFluctuation_1M
	}
	return 0
}

func (x *KlineFluctuation) GetKlineFluctuation_5M() float64 {
	if x != nil {
		return x.KlineFluctuation_5M
	}
	return 0
}

func (x *KlineFluctuation) GetKlineFluctuation_15M() float64 {
	if x != nil {
		return x.KlineFluctuation_15M
	}
	return 0
}

func (x *KlineFluctuation) GetKlineFluctuation_1H() float64 {
	if x != nil {
		return x.KlineFluctuation_1H
	}
	return 0
}

func (x *KlineFluctuation) GetKlineFluctuation_4H() float64 {
	if x != nil {
		return x.KlineFluctuation_4H
	}
	return 0
}

func (x *KlineFluctuation) GetKlineFluctuation_12H() float64 {
	if x != nil {
		return x.KlineFluctuation_12H
	}
	return 0
}

func (x *KlineFluctuation) GetKlineFluctuation_24H() float64 {
	if x != nil {
		return x.KlineFluctuation_24H
	}
	return 0
}

var File_dataflow_proto protoreflect.FileDescriptor

const file_dataflow_proto_rawDesc = "" +
	"\n" +
	"\x0edataflow.proto\x12\bdataflow\"-\n" +
	"\x06Klines\x12#\n" +
	"\x04list\x18\x01 \x03(\v2\x0f.dataflow.KlineR\x04list\"\x87\x05\n" +
	"\x05Kline\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x03R\achainId\x12\x1a\n" +
	"\binterval\x18\x02 \x01(\tR\binterval\x12\x1b\n" +
	"\tpair_addr\x18\x03 \x01(\tR\bpairAddr\x12\x12\n" +
	"\x04open\x18\x04 \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\x05 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x06 \x01(\x01R\x03low\x12\x14\n" +
	"\x05close\x18\a \x01(\x01R\x05close\x12\x1b\n" +
	"\tmcap_open\x18\b \x01(\x01R\bmcapOpen\x12\x1b\n" +
	"\tmcap_high\x18\t \x01(\x01R\bmcapHigh\x12\x19\n" +
	"\bmcap_low\x18\n" +
	" \x01(\x01R\amcapLow\x12\x1d\n" +
	"\n" +
	"mcap_close\x18\v \x01(\x01R\tmcapClose\x12\x1d\n" +
	"\n" +
	"amount_usd\x18\f \x01(\x01R\tamountUsd\x12!\n" +
	"\fvolume_token\x18\r \x01(\x01R\vvolumeToken\x12\x1f\n" +
	"\vcandle_time\x18\x0e \x01(\x03R\n" +
	"candleTime\x12\x1b\n" +
	"\tbuy_count\x18\x0f \x01(\x03R\bbuyCount\x12\x1d\n" +
	"\n" +
	"sell_count\x18\x10 \x01(\x03R\tsellCount\x12\x1f\n" +
	"\vtotal_count\x18\x11 \x01(\x03R\n" +
	"totalCount\x12\x19\n" +
	"\bclose_at\x18\x12 \x01(\x03R\acloseAt\x12\x17\n" +
	"\aopen_at\x18\x13 \x01(\x03R\x06openAt\x12\x1b\n" +
	"\tavg_price\x18\x14 \x01(\x01R\bavgPrice\x12\x17\n" +
	"\amkt_cap\x18\x15 \x01(\x01R\x06mktCap\x12\x1d\n" +
	"\n" +
	"pump_point\x18\x16 \x01(\x01R\tpumpPoint\x12\x1d\n" +
	"\n" +
	"token_addr\x18\x17 \x01(\tR\ttokenAddr\"`\n" +
	"\x0fKline24InfoItem\x12\x1b\n" +
	"\tchange_24\x18\x01 \x01(\x01R\bchange24\x12\x17\n" +
	"\atxs_24h\x18\x02 \x01(\rR\x06txs24h\x12\x17\n" +
	"\avol_24h\x18\x03 \x01(\x01R\x06vol24h\"\xf6\x02\n" +
	"\x10KlineFluctuation\x120\n" +
	"\x14kline_fluctuation_1m\x18\x01 \x01(\x01R\x12klineFluctuation1m\x120\n" +
	"\x14kline_fluctuation_5m\x18\x02 \x01(\x01R\x12klineFluctuation5m\x122\n" +
	"\x15kline_fluctuation_15m\x18\x03 \x01(\x01R\x13klineFluctuation15m\x120\n" +
	"\x14kline_fluctuation_1h\x18\x04 \x01(\x01R\x12klineFluctuation1h\x120\n" +
	"\x14kline_fluctuation_4h\x18\x05 \x01(\x01R\x12klineFluctuation4h\x122\n" +
	"\x15kline_fluctuation_12h\x18\x06 \x01(\x01R\x13klineFluctuation12h\x122\n" +
	"\x15kline_fluctuation_24h\x18\a \x01(\x01R\x13klineFluctuation24h2\n" +
	"\n" +
	"\bDataflowB\fZ\n" +
	"./dataflowb\x06proto3"

var (
	file_dataflow_proto_rawDescOnce sync.Once
	file_dataflow_proto_rawDescData []byte
)

func file_dataflow_proto_rawDescGZIP() []byte {
	file_dataflow_proto_rawDescOnce.Do(func() {
		file_dataflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dataflow_proto_rawDesc), len(file_dataflow_proto_rawDesc)))
	})
	return file_dataflow_proto_rawDescData
}

var file_dataflow_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_dataflow_proto_goTypes = []any{
	(*Klines)(nil),           // 0: dataflow.Klines
	(*Kline)(nil),            // 1: dataflow.Kline
	(*Kline24InfoItem)(nil),  // 2: dataflow.Kline24InfoItem
	(*KlineFluctuation)(nil), // 3: dataflow.KlineFluctuation
}
var file_dataflow_proto_depIdxs = []int32{
	1, // 0: dataflow.Klines.list:type_name -> dataflow.Kline
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dataflow_proto_init() }
func file_dataflow_proto_init() {
	if File_dataflow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dataflow_proto_rawDesc), len(file_dataflow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dataflow_proto_goTypes,
		DependencyIndexes: file_dataflow_proto_depIdxs,
		MessageInfos:      file_dataflow_proto_msgTypes,
	}.Build()
	File_dataflow_proto = out.File
	file_dataflow_proto_goTypes = nil
	file_dataflow_proto_depIdxs = nil
}
