// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: dataflow.proto

package dataflow

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

// DataflowClient is the client API for Dataflow service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataflowClient interface {
}

type dataflowClient struct {
	cc grpc.ClientConnInterface
}

func NewDataflowClient(cc grpc.ClientConnInterface) DataflowClient {
	return &dataflowClient{cc}
}

// DataflowServer is the server API for Dataflow service.
// All implementations must embed UnimplementedDataflowServer
// for forward compatibility.
type DataflowServer interface {
	mustEmbedUnimplementedDataflowServer()
}

// UnimplementedDataflowServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataflowServer struct{}

func (UnimplementedDataflowServer) mustEmbedUnimplementedDataflowServer() {}
func (UnimplementedDataflowServer) testEmbeddedByValue()                  {}

// UnsafeDataflowServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataflowServer will
// result in compilation errors.
type UnsafeDataflowServer interface {
	mustEmbedUnimplementedDataflowServer()
}

func RegisterDataflowServer(s grpc.ServiceRegistrar, srv DataflowServer) {
	// If the following call pancis, it indicates UnimplementedDataflowServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Dataflow_ServiceDesc, srv)
}

// Dataflow_ServiceDesc is the grpc.ServiceDesc for Dataflow service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Dataflow_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dataflow.Dataflow",
	HandlerType: (*DataflowServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "dataflow.proto",
}
