// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: market.proto

package marketclient

import (
	"context"

	"dex/market/market"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AuditInfo                                = market.AuditInfo
	AuditInfoRequest                         = market.AuditInfoRequest
	AuditInfoResponse                        = market.AuditInfoResponse
	AuditTokenRequest                        = market.AuditTokenRequest
	AuditTokenResponse                       = market.AuditTokenResponse
	CheckPairInfoRiskRequest                 = market.CheckPairInfoRiskRequest
	CheckPairInfoRiskResponse                = market.CheckPairInfoRiskResponse
	ClmmPoolItem                             = market.ClmmPoolItem
	FavoriteTokenRequest                     = market.FavoriteTokenRequest
	FavoriteTokenResponse                    = market.FavoriteTokenResponse
	GetAmmPoolByPairRequest                  = market.GetAmmPoolByPairRequest
	GetAmmPoolByPairResponse                 = market.GetAmmPoolByPairResponse
	GetBannerConfigRequest                   = market.GetBannerConfigRequest
	GetBannerConfigResponse                  = market.GetBannerConfigResponse
	GetChainTokenInfoRequest                 = market.GetChainTokenInfoRequest
	GetChainTokenInfoResponse                = market.GetChainTokenInfoResponse
	GetClmmPoolListRequest                   = market.GetClmmPoolListRequest
	GetClmmPoolListResponse                  = market.GetClmmPoolListResponse
	GetConfigRequest                         = market.GetConfigRequest
	GetConfigResponse                        = market.GetConfigResponse
	GetContractOrToeknInfoResponse           = market.GetContractOrToeknInfoResponse
	GetContractOrTokenInfoRequest            = market.GetContractOrTokenInfoRequest
	GetFluctuationsByPairAddressRequest      = market.GetFluctuationsByPairAddressRequest
	GetFluctuationsByPairAddressResponse     = market.GetFluctuationsByPairAddressResponse
	GetGasInfo                               = market.GetGasInfo
	GetGasInfoRequest                        = market.GetGasInfoRequest
	GetGasInfoResponse                       = market.GetGasInfoResponse
	GetHoldTokenUsersRequest                 = market.GetHoldTokenUsersRequest
	GetHoldTokenUsersResponse                = market.GetHoldTokenUsersResponse
	GetKOLPlanRequest                        = market.GetKOLPlanRequest
	GetKOLPlanResponse                       = market.GetKOLPlanResponse
	GetKlineByPairsRequest                   = market.GetKlineByPairsRequest
	GetKlineByPairsResponse                  = market.GetKlineByPairsResponse
	GetKlineRequest                          = market.GetKlineRequest
	GetKlineResponse                         = market.GetKlineResponse
	GetKlineTagRequest                       = market.GetKlineTagRequest
	GetKlineTagResponse                      = market.GetKlineTagResponse
	GetLatestTradeInfoRequest                = market.GetLatestTradeInfoRequest
	GetLatestTradeInfoResponse               = market.GetLatestTradeInfoResponse
	GetMarketInfoRequest                     = market.GetMarketInfoRequest
	GetMarketInfoResponse                    = market.GetMarketInfoResponse
	GetNativeTokenPriceRequest               = market.GetNativeTokenPriceRequest
	GetNativeTokenPriceResponse              = market.GetNativeTokenPriceResponse
	GetPairInfoByTokenRequest                = market.GetPairInfoByTokenRequest
	GetPairInfoByTokenResponse               = market.GetPairInfoByTokenResponse
	GetPairInfoByTokensRequest               = market.GetPairInfoByTokensRequest
	GetPairInfoByTokensResponse              = market.GetPairInfoByTokensResponse
	GetPairInfoRequest                       = market.GetPairInfoRequest
	GetPairInfoResponse                      = market.GetPairInfoResponse
	GetPairsByTimeRequest                    = market.GetPairsByTimeRequest
	GetPairsByTimeResponse                   = market.GetPairsByTimeResponse
	GetPoolByPairRequest                     = market.GetPoolByPairRequest
	GetPoolByPairResponse                    = market.GetPoolByPairResponse
	GetPumpTokenInfoRequest                  = market.GetPumpTokenInfoRequest
	GetPumpTokenListRequest                  = market.GetPumpTokenListRequest
	GetPumpTokenListResponse                 = market.GetPumpTokenListResponse
	GetTokenBasicItem                        = market.GetTokenBasicItem
	GetTokenBasicListResponse                = market.GetTokenBasicListResponse
	GetTokenHolderListItem                   = market.GetTokenHolderListItem
	GetTokenHolderListRequest                = market.GetTokenHolderListRequest
	GetTokenHolderListResponse               = market.GetTokenHolderListResponse
	GetTokenInfoByPairRequest                = market.GetTokenInfoByPairRequest
	GetTokenInfoRequest                      = market.GetTokenInfoRequest
	GetTokenInfoResponse                     = market.GetTokenInfoResponse
	GetTokenListByAddressesItem              = market.GetTokenListByAddressesItem
	GetTokenListByAddressesRequest           = market.GetTokenListByAddressesRequest
	GetTokenListByAddressesResponse          = market.GetTokenListByAddressesResponse
	GetTokenListRequest                      = market.GetTokenListRequest
	GetTokenListResponse                     = market.GetTokenListResponse
	GetTokenMarketCapListByAddressesItem     = market.GetTokenMarketCapListByAddressesItem
	GetTokenMarketCapListByAddressesRequest  = market.GetTokenMarketCapListByAddressesRequest
	GetTokenMarketCapListByAddressesResponse = market.GetTokenMarketCapListByAddressesResponse
	GetTokenMarketCapListRequestItem         = market.GetTokenMarketCapListRequestItem
	GetTokenMarketInfoRequest                = market.GetTokenMarketInfoRequest
	GetTokenMarketInfoResponse               = market.GetTokenMarketInfoResponse
	GetTop10Request                          = market.GetTop10Request
	GetTop10Response                         = market.GetTop10Response
	GetUpdateConfigRequest                   = market.GetUpdateConfigRequest
	GetUpdateConfigResponse                  = market.GetUpdateConfigResponse
	GetWalletTradeInfoByPairRequest          = market.GetWalletTradeInfoByPairRequest
	GetWalletTradeInfoByPairResponse         = market.GetWalletTradeInfoByPairResponse
	Kline                                    = market.Kline
	Kline24InfoItem                          = market.Kline24InfoItem
	KlineFluctuation                         = market.KlineFluctuation
	KlineUp                                  = market.KlineUp
	Klines                                   = market.Klines
	NewKline                                 = market.NewKline
	PairInfo                                 = market.PairInfo
	Pass                                     = market.Pass
	PumpFunKeys                              = market.PumpFunKeys
	PumpTokenItem                            = market.PumpTokenItem
	PushTokenInfoRequest                     = market.PushTokenInfoRequest
	PushTokenInfoResponse                    = market.PushTokenInfoResponse
	QueryPairContractSafeRequest             = market.QueryPairContractSafeRequest
	QueryUserHoldersRequest                  = market.QueryUserHoldersRequest
	RaydiumAmmKeys                           = market.RaydiumAmmKeys
	RaydiumClmmKeys                          = market.RaydiumClmmKeys
	SafetyCheck                              = market.SafetyCheck
	SearchPairByAddrRequest                  = market.SearchPairByAddrRequest
	SearchTokenPairRequest                   = market.SearchTokenPairRequest
	SearchTokenPairResponse                  = market.SearchTokenPairResponse
	SearchTrendingRequest                    = market.SearchTrendingRequest
	SearchTrendingResponse                   = market.SearchTrendingResponse
	Token                                    = market.Token
	TokenInfoItem                            = market.TokenInfoItem
	TokenSecurityCheckRequest                = market.TokenSecurityCheckRequest
	TokenSecurityCheckResponse               = market.TokenSecurityCheckResponse
	Trade                                    = market.Trade
	Trades                                   = market.Trades

	Market interface {
		GetPumpTokenList(ctx context.Context, in *GetPumpTokenListRequest, opts ...grpc.CallOption) (*GetPumpTokenListResponse, error)
		GetClmmPoolList(ctx context.Context, in *GetClmmPoolListRequest, opts ...grpc.CallOption) (*GetClmmPoolListResponse, error)
		GetKline(ctx context.Context, in *GetKlineRequest, opts ...grpc.CallOption) (*GetKlineResponse, error)
		GetPairInfoByToken(ctx context.Context, in *GetPairInfoByTokenRequest, opts ...grpc.CallOption) (*GetPairInfoByTokenResponse, error)
		GetNativeTokenPrice(ctx context.Context, in *GetNativeTokenPriceRequest, opts ...grpc.CallOption) (*GetNativeTokenPriceResponse, error)
		PushTokenInfo(ctx context.Context, in *PushTokenInfoRequest, opts ...grpc.CallOption) (*PushTokenInfoResponse, error)
		GetTokenInfo(ctx context.Context, in *GetTokenInfoRequest, opts ...grpc.CallOption) (*GetTokenInfoResponse, error)
		TokenSecurityCheck(ctx context.Context, in *TokenSecurityCheckRequest, opts ...grpc.CallOption) (*TokenSecurityCheckResponse, error)
	}

	defaultMarket struct {
		cli zrpc.Client
	}
)

func NewMarket(cli zrpc.Client) Market {
	return &defaultMarket{
		cli: cli,
	}
}

func (m *defaultMarket) GetPumpTokenList(ctx context.Context, in *GetPumpTokenListRequest, opts ...grpc.CallOption) (*GetPumpTokenListResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.GetPumpTokenList(ctx, in, opts...)
}

func (m *defaultMarket) GetClmmPoolList(ctx context.Context, in *GetClmmPoolListRequest, opts ...grpc.CallOption) (*GetClmmPoolListResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.GetClmmPoolList(ctx, in, opts...)
}

func (m *defaultMarket) GetKline(ctx context.Context, in *GetKlineRequest, opts ...grpc.CallOption) (*GetKlineResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.GetKline(ctx, in, opts...)
}

func (m *defaultMarket) GetPairInfoByToken(ctx context.Context, in *GetPairInfoByTokenRequest, opts ...grpc.CallOption) (*GetPairInfoByTokenResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.GetPairInfoByToken(ctx, in, opts...)
}

func (m *defaultMarket) GetNativeTokenPrice(ctx context.Context, in *GetNativeTokenPriceRequest, opts ...grpc.CallOption) (*GetNativeTokenPriceResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.GetNativeTokenPrice(ctx, in, opts...)
}

func (m *defaultMarket) PushTokenInfo(ctx context.Context, in *PushTokenInfoRequest, opts ...grpc.CallOption) (*PushTokenInfoResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.PushTokenInfo(ctx, in, opts...)
}

func (m *defaultMarket) GetTokenInfo(ctx context.Context, in *GetTokenInfoRequest, opts ...grpc.CallOption) (*GetTokenInfoResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.GetTokenInfo(ctx, in, opts...)
}

func (m *defaultMarket) TokenSecurityCheck(ctx context.Context, in *TokenSecurityCheckRequest, opts ...grpc.CallOption) (*TokenSecurityCheckResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.TokenSecurityCheck(ctx, in, opts...)
}
