// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: consumer.proto

package consumerclient

import (
	"context"

	"dex/consumer/consumer"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	PingRequest  = consumer.PingRequest
	PingResponse = consumer.PingResponse

	Consumer interface {
		// Ping
		Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	}

	defaultConsumer struct {
		cli zrpc.Client
	}
)

func NewConsumer(cli zrpc.Client) Consumer {
	return &defaultConsumer{
		cli: cli,
	}
}

// Ping
func (m *defaultConsumer) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	client := consumer.NewConsumerClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
