CREATE TABLE `trade_order` (
  `id` int NOT NULL AUTO_INCREMENT,
  `uid` int NOT NULL,
  `trade_type` tinyint NOT NULL COMMENT '1:market 2：limit  3:one_click 4:token_cap_limit 5:trailing_stop',
  `chain_id` int NOT NULL,
  `token_ca` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `swap_type` tinyint NOT NULL COMMENT '1:buy 2:sell',
  `wallet_index` tinyint NOT NULL,
  `wallet_address` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `is_auto_slippage` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否自动滑点',
  `slippage` int NOT NULL,
  `is_anti_mev` tinyint(1) NOT NULL,
  `gas_type` tinyint NOT NULL COMMENT '手续费类型 1 normal 2：fast 3：superspeed',
  `status` tinyint NOT NULL COMMENT '1：wait 2:proc 3:onchain 4:fail 5:suc 6:cancel 7:timeout fail ',
  `fail_reason` varchar(255) NOT NULL DEFAULT '',
  `double_out` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否翻倍出本 1:是 0:否',
  `order_cap` decimal(32,18) NOT NULL DEFAULT '0.000000000000000000' COMMENT '挂单市值 token的流动性市值',
  `order_amount` decimal(32,18) NOT NULL COMMENT '挂单数量（付出的币种 买:base 卖:token）',
  `order_price_base` decimal(32,18) NOT NULL COMMENT '挂单价格 token对base的价格',
  `order_value_base` decimal(32,18) NOT NULL COMMENT '挂单总价 （base）买： 挂单数量   卖：挂单数量*挂单总价',
  `order_base_price` decimal(32,18) NOT NULL COMMENT 'base to usd',
  `final_cap` decimal(32,18) NOT NULL DEFAULT '0.000000000000000000' COMMENT '最终市值 token的流动性市值',
  `final_amount` decimal(32,18) NOT NULL DEFAULT '0.000000000000000000' COMMENT '最终数量（得到的币种 买:token 卖:base）',
  `final_price_base` decimal(32,18) NOT NULL DEFAULT '0.000000000000000000' COMMENT '最终价格 token对base的价格',
  `final_value_base` decimal(32,18) NOT NULL DEFAULT '0.000000000000000000' COMMENT '最终总价值（base）买：最终数量 * 最终价格   卖：最终数量',
  `final_base_price` decimal(32,18) NOT NULL COMMENT 'base to usd',
  `gas_fee` decimal(32,18) NOT NULL COMMENT 'sol',
  `priority_fee` decimal(32,18) NOT NULL DEFAULT '0.000000000000000000' COMMENT 'sol',
  `dex_fee` decimal(32,18) NOT NULL DEFAULT '0.000000000000000000' COMMENT '花费币种',
  `server_fee` decimal(32,18) NOT NULL DEFAULT '0.000000000000000000' COMMENT 'sol',
  `jito_fee` decimal(32,18) NOT NULL DEFAULT '0.000000000000000000' COMMENT 'sol',
  `tx_hash` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `dex_name` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '交易时选取的交易所',
  `pair_ca` varchar(100) NOT NULL COMMENT '交易时选取的交易池',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `drawdown_price` decimal(32,18) NOT NULL DEFAULT '0.000000000000000000' COMMENT '回撤触发价格',
  `trailing_percent` int NOT NULL DEFAULT '0' COMMENT '回撤百分比',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `user` (`uid`,`status`,`trade_type`) USING BTREE,
  KEY `status_chain_id` (`status`, `chain_id`) USING BTREE,
  KEY `trade_order_created_at_uid_status_index` (`created_at`,`uid`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


CREATE TABLE `trade_order_log` (
  `id` int NOT NULL AUTO_INCREMENT,
  `order_id` int NOT NULL,
  `uid` int NOT NULL,
  `trade_type` tinyint NOT NULL COMMENT '1:market 2：limit',
  `chain_id` int NOT NULL,
  `token_ca` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `swap_type` tinyint NOT NULL COMMENT '1:buy 2:sell',
  `wallet_index` tinyint NOT NULL,
  `wallet_address` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `is_auto_slippage` tinyint(1) NOT NULL DEFAULT '0',
  `slippage` int NOT NULL,
  `is_anti_mev` tinyint(1) NOT NULL,
  `gas_type` tinyint NOT NULL COMMENT '手续费类型 1 normal 2：fast 3：superspeed',
  `status` tinyint NOT NULL COMMENT '1：wait 2:proc 3:onchain 4:fail 5:suc 6:cancel 7:timeout fail ',
  `fail_reason` varchar(255) NOT NULL DEFAULT '',
  `double_out` tinyint(1) NOT NULL COMMENT '是否翻倍出本 1:是 0:否',
  `order_cap` decimal(32,18) NOT NULL COMMENT '挂单市值 token的流动性市值',
  `order_amount` decimal(32,18) NOT NULL COMMENT '挂单数量（付出的币种 买:base 卖:token）',
  `order_price_base` decimal(32,18) NOT NULL COMMENT '挂单价格 token对base的价格',
  `order_value_base` decimal(32,18) NOT NULL COMMENT '挂单总价 （base）买： 挂单数量   卖：挂单数量*挂单总价',
  `order_base_price` decimal(32,18) NOT NULL COMMENT 'base to usd',
  `final_cap` decimal(32,18) NOT NULL DEFAULT '0.000000000000000000' COMMENT '最终市值 token的流动性市值',
  `final_amount` decimal(32,18) NOT NULL COMMENT '最终数量（得到的币种 买:token 卖:base）',
  `final_price_base` decimal(32,18) NOT NULL DEFAULT '0.000000000000000000' COMMENT '最终价格 token对base的价格',
  `final_value_base` decimal(32,18) NOT NULL DEFAULT '0.000000000000000000' COMMENT '最终总价值（base）买：最终数量 * 最终价格   卖：最终数量',
  `final_base_price` decimal(32,18) NOT NULL COMMENT 'base to usd',
  `gas_fee` decimal(32,18) NOT NULL COMMENT 'sol',
  `priority_fee` decimal(32,18) NOT NULL COMMENT 'sol',
  `dex_fee` decimal(32,18) NOT NULL COMMENT 'intoken',
  `server_fee` decimal(32,18) NOT NULL COMMENT 'sol',
  `jito_fee` decimal(32,18) NOT NULL DEFAULT '0.000000000000000000' COMMENT 'sol',
  `tx_hash` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `dex_name` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '交易时选取的交易所',
  `pair_ca` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '交易时选取的交易池',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `drawdown_price` decimal(32,18) NOT NULL COMMENT '回撤触发价格',
  `trailing_percent` int NOT NULL COMMENT '回撤百分比',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `order_id_index` (`order_id`,`status`) USING BTREE,
  KEY `trade_order_log_create_time_status_chain_id_index` (`created_at`,`status`,`chain_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;