// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.4

package solmodel__home

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	pumpAmmInfoFieldNames          = builder.RawFieldNames(&PumpAmmInfo{})
	pumpAmmInfoRows                = strings.Join(pumpAmmInfoFieldNames, ",")
	pumpAmmInfoRowsExpectAutoSet   = strings.Join(stringx.Remove(pumpAmmInfoFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	pumpAmmInfoRowsWithPlaceHolder = strings.Join(stringx.Remove(pumpAmmInfoFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	pumpAmmInfoModel interface {
		Insert(ctx context.Context, data *PumpAmmInfo) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*PumpAmmInfo, error)
		FindOneByPoolAccount(ctx context.Context, poolAccount string) (*PumpAmmInfo, error)
		Update(ctx context.Context, data *PumpAmmInfo) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPumpAmmInfoModel struct {
		conn  sqlx.SqlConn
		table string
	}

	PumpAmmInfo struct {
		Id                               int64        `db:"id"`                                   // Primary Key
		PoolAccount                      string       `db:"pool_account"`                         // Pool account address
		GlobalConfigAccount              string       `db:"global_config_account"`                // Global configuration account address
		BaseMintAccount                  string       `db:"base_mint_account"`                    // Base mint address
		QuoteMintAccount                 string       `db:"quote_mint_account"`                   // Quote mint address
		PoolBaseTokenAccount             string       `db:"pool_base_token_account"`              // Pool''s base token account
		PoolQuoteTokenAccount            string       `db:"pool_quote_token_account"`             // Pool''s quote token account
		ProtocolFeeRecipientAccount      string       `db:"protocol_fee_recipient_account"`       // Protocol fee recipient account
		ProtocolFeeRecipientTokenAccount string       `db:"protocol_fee_recipient_token_account"` // Protocol fee recipient token account
		BaseTokenProgram                 string       `db:"base_token_program"`                   // Base token program address
		QuoteTokenProgram                string       `db:"quote_token_program"`                  // Quote token program address
		SystemProgram                    string       `db:"system_program"`                       // System program address
		AssociatedTokenProgram           string       `db:"associated_token_program"`             // Associated token program address
		EventAuthorityAccount            string       `db:"event_authority_account"`              // Event authority account
		ProgramAccount                   string       `db:"program_account"`                      // Program account address
		CoinCreatorVaultAtaAccount       string       `db:"coin_creator_vault_ata_account"`       // Coin creator vault ata account
		CoinCreatorVaultAuthorityAccount string       `db:"coin_creator_vault_authority_account"` // Coin creator vault authority account
		CreatedAt                        time.Time    `db:"created_at"`                           // Creation timestamp
		UpdatedAt                        time.Time    `db:"updated_at"`                           // Update timestamp
		DeletedAt                        sql.NullTime `db:"deleted_at"`                           // Soft delete timestamp
	}
)

func newPumpAmmInfoModel(conn sqlx.SqlConn) *defaultPumpAmmInfoModel {
	return &defaultPumpAmmInfoModel{
		conn:  conn,
		table: "`pump_amm_info`",
	}
}

func (m *defaultPumpAmmInfoModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultPumpAmmInfoModel) FindOne(ctx context.Context, id int64) (*PumpAmmInfo, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", pumpAmmInfoRows, m.table)
	var resp PumpAmmInfo
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPumpAmmInfoModel) FindOneByPoolAccount(ctx context.Context, poolAccount string) (*PumpAmmInfo, error) {
	var resp PumpAmmInfo
	query := fmt.Sprintf("select %s from %s where `pool_account` = ? limit 1", pumpAmmInfoRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, poolAccount)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPumpAmmInfoModel) Insert(ctx context.Context, data *PumpAmmInfo) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, pumpAmmInfoRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.PoolAccount, data.GlobalConfigAccount, data.BaseMintAccount, data.QuoteMintAccount, data.PoolBaseTokenAccount, data.PoolQuoteTokenAccount, data.ProtocolFeeRecipientAccount, data.ProtocolFeeRecipientTokenAccount, data.BaseTokenProgram, data.QuoteTokenProgram, data.SystemProgram, data.AssociatedTokenProgram, data.EventAuthorityAccount, data.ProgramAccount, data.CoinCreatorVaultAtaAccount, data.CoinCreatorVaultAuthorityAccount, data.DeletedAt)
	return ret, err
}

func (m *defaultPumpAmmInfoModel) Update(ctx context.Context, newData *PumpAmmInfo) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, pumpAmmInfoRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.PoolAccount, newData.GlobalConfigAccount, newData.BaseMintAccount, newData.QuoteMintAccount, newData.PoolBaseTokenAccount, newData.PoolQuoteTokenAccount, newData.ProtocolFeeRecipientAccount, newData.ProtocolFeeRecipientTokenAccount, newData.BaseTokenProgram, newData.QuoteTokenProgram, newData.SystemProgram, newData.AssociatedTokenProgram, newData.EventAuthorityAccount, newData.ProgramAccount, newData.CoinCreatorVaultAtaAccount, newData.CoinCreatorVaultAuthorityAccount, newData.DeletedAt, newData.Id)
	return err
}

func (m *defaultPumpAmmInfoModel) tableName() string {
	return m.table
}
