// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: consumer.proto

package server

import (
	"context"

	"dex/consumer/consumer"
	"dex/consumer/internal/logic"
	"dex/consumer/internal/svc"
)

type ConsumerServer struct {
	svcCtx *svc.ServiceContext
	consumer.UnimplementedConsumerServer
}

func NewConsumerServer(svcCtx *svc.ServiceContext) *ConsumerServer {
	return &ConsumerServer{
		svcCtx: svcCtx,
	}
}

// Ping
func (s *ConsumerServer) Ping(ctx context.Context, in *consumer.PingRequest) (*consumer.PingResponse, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
