// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: trade.proto

package tradeclient

import (
	"context"

	"dex/trade/trade"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddLiquidityRequest        = trade.AddLiquidityRequest
	AddLiquidityResponse       = trade.AddLiquidityResponse
	CancelOrderRequest         = trade.CancelOrderRequest
	CancelOrderResponse        = trade.CancelOrderResponse
	CreateLimitOrderRequest    = trade.CreateLimitOrderRequest
	CreateLimitOrderResponse   = trade.CreateLimitOrderResponse
	CreateMarketOrderRequest   = trade.CreateMarketOrderRequest
	CreateMarketOrderResponse  = trade.CreateMarketOrderResponse
	CreatePoolRequest          = trade.CreatePoolRequest
	CreatePoolResponse         = trade.CreatePoolResponse
	CreateTrailingStopRequest  = trade.CreateTrailingStopRequest
	CreateTrailingStopResponse = trade.CreateTrailingStopResponse
	GetGasInfo                 = trade.GetGasInfo
	GetGasInfoRequest          = trade.GetGasInfoRequest
	GetGasInfoResponse         = trade.GetGasInfoResponse
	ProcTokenCapRequest        = trade.ProcTokenCapRequest
	ProcTokenCapResponse       = trade.ProcTokenCapResponse
	ProcTokenPriceRequest      = trade.ProcTokenPriceRequest
	ProcTokenPriceResponse     = trade.ProcTokenPriceResponse
	QueryCurrentOrdersRequest  = trade.QueryCurrentOrdersRequest
	QueryCurrentOrdersResponse = trade.QueryCurrentOrdersResponse
	QueryHoldTokenInfo         = trade.QueryHoldTokenInfo
	QueryHoldTokenInfoDetail   = trade.QueryHoldTokenInfoDetail
	QueryHoldTokenRequest      = trade.QueryHoldTokenRequest
	QueryHoldTokenResponse     = trade.QueryHoldTokenResponse
	QueryOrderHistoryRequest   = trade.QueryOrderHistoryRequest
	QueryOrderHistoryResponse  = trade.QueryOrderHistoryResponse
	QueryOrderInfo             = trade.QueryOrderInfo
	QueryTradeHistoryRequest   = trade.QueryTradeHistoryRequest
	QueryTradeHistoryResponse  = trade.QueryTradeHistoryResponse
	QueryTransferRequest       = trade.QueryTransferRequest
	QueryTransferResponse      = trade.QueryTransferResponse
	TestRpcRequest             = trade.TestRpcRequest
	TestRpcResponse            = trade.TestRpcResponse
	TokenInfo                  = trade.TokenInfo
	TransferRequest            = trade.TransferRequest
	TransferResponse           = trade.TransferResponse

	Trade interface {
		CreateLimitOrder(ctx context.Context, in *CreateLimitOrderRequest, opts ...grpc.CallOption) (*CreateLimitOrderResponse, error)
		CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error)
		CreateMarketOrder(ctx context.Context, in *CreateMarketOrderRequest, opts ...grpc.CallOption) (*CreateMarketOrderResponse, error)
		CreatePool(ctx context.Context, in *CreatePoolRequest, opts ...grpc.CallOption) (*CreatePoolResponse, error)
		QueryCurrentOrders(ctx context.Context, in *QueryCurrentOrdersRequest, opts ...grpc.CallOption) (*QueryCurrentOrdersResponse, error)
		QueryTradeHistory(ctx context.Context, in *QueryTradeHistoryRequest, opts ...grpc.CallOption) (*QueryTradeHistoryResponse, error)
		QueryOrderHistory(ctx context.Context, in *QueryOrderHistoryRequest, opts ...grpc.CallOption) (*QueryOrderHistoryResponse, error)
		ProcTokenPrice(ctx context.Context, in *ProcTokenPriceRequest, opts ...grpc.CallOption) (*ProcTokenPriceResponse, error)
		ProcTokenCap(ctx context.Context, in *ProcTokenCapRequest, opts ...grpc.CallOption) (*ProcTokenCapResponse, error)
		CreateTrailingStop(ctx context.Context, in *CreateTrailingStopRequest, opts ...grpc.CallOption) (*CreateTrailingStopResponse, error)
		ProcTrailingStop(ctx context.Context, in *ProcTokenPriceRequest, opts ...grpc.CallOption) (*ProcTokenPriceResponse, error)
		QueryHoldingToken(ctx context.Context, in *QueryHoldTokenRequest, opts ...grpc.CallOption) (*QueryHoldTokenResponse, error)
		GetGasInfo(ctx context.Context, in *GetGasInfoRequest, opts ...grpc.CallOption) (*GetGasInfoResponse, error)
		AddLiquidityV1(ctx context.Context, in *AddLiquidityRequest, opts ...grpc.CallOption) (*AddLiquidityResponse, error)
		TestRpc(ctx context.Context, in *TestRpcRequest, opts ...grpc.CallOption) (*TestRpcResponse, error)
		// internal
		Transfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error)
		QueryTransfer(ctx context.Context, in *QueryTransferRequest, opts ...grpc.CallOption) (*QueryTransferResponse, error)
	}

	defaultTrade struct {
		cli zrpc.Client
	}
)

func NewTrade(cli zrpc.Client) Trade {
	return &defaultTrade{
		cli: cli,
	}
}

func (m *defaultTrade) CreateLimitOrder(ctx context.Context, in *CreateLimitOrderRequest, opts ...grpc.CallOption) (*CreateLimitOrderResponse, error) {
	client := trade.NewTradeClient(m.cli.Conn())
	return client.CreateLimitOrder(ctx, in, opts...)
}

func (m *defaultTrade) CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error) {
	client := trade.NewTradeClient(m.cli.Conn())
	return client.CancelOrder(ctx, in, opts...)
}

func (m *defaultTrade) CreateMarketOrder(ctx context.Context, in *CreateMarketOrderRequest, opts ...grpc.CallOption) (*CreateMarketOrderResponse, error) {
	client := trade.NewTradeClient(m.cli.Conn())
	return client.CreateMarketOrder(ctx, in, opts...)
}

func (m *defaultTrade) CreatePool(ctx context.Context, in *CreatePoolRequest, opts ...grpc.CallOption) (*CreatePoolResponse, error) {
	client := trade.NewTradeClient(m.cli.Conn())
	return client.CreatePool(ctx, in, opts...)
}

func (m *defaultTrade) QueryCurrentOrders(ctx context.Context, in *QueryCurrentOrdersRequest, opts ...grpc.CallOption) (*QueryCurrentOrdersResponse, error) {
	client := trade.NewTradeClient(m.cli.Conn())
	return client.QueryCurrentOrders(ctx, in, opts...)
}

func (m *defaultTrade) QueryTradeHistory(ctx context.Context, in *QueryTradeHistoryRequest, opts ...grpc.CallOption) (*QueryTradeHistoryResponse, error) {
	client := trade.NewTradeClient(m.cli.Conn())
	return client.QueryTradeHistory(ctx, in, opts...)
}

func (m *defaultTrade) QueryOrderHistory(ctx context.Context, in *QueryOrderHistoryRequest, opts ...grpc.CallOption) (*QueryOrderHistoryResponse, error) {
	client := trade.NewTradeClient(m.cli.Conn())
	return client.QueryOrderHistory(ctx, in, opts...)
}

func (m *defaultTrade) ProcTokenPrice(ctx context.Context, in *ProcTokenPriceRequest, opts ...grpc.CallOption) (*ProcTokenPriceResponse, error) {
	client := trade.NewTradeClient(m.cli.Conn())
	return client.ProcTokenPrice(ctx, in, opts...)
}

func (m *defaultTrade) ProcTokenCap(ctx context.Context, in *ProcTokenCapRequest, opts ...grpc.CallOption) (*ProcTokenCapResponse, error) {
	client := trade.NewTradeClient(m.cli.Conn())
	return client.ProcTokenCap(ctx, in, opts...)
}

func (m *defaultTrade) CreateTrailingStop(ctx context.Context, in *CreateTrailingStopRequest, opts ...grpc.CallOption) (*CreateTrailingStopResponse, error) {
	client := trade.NewTradeClient(m.cli.Conn())
	return client.CreateTrailingStop(ctx, in, opts...)
}

func (m *defaultTrade) ProcTrailingStop(ctx context.Context, in *ProcTokenPriceRequest, opts ...grpc.CallOption) (*ProcTokenPriceResponse, error) {
	client := trade.NewTradeClient(m.cli.Conn())
	return client.ProcTrailingStop(ctx, in, opts...)
}

func (m *defaultTrade) QueryHoldingToken(ctx context.Context, in *QueryHoldTokenRequest, opts ...grpc.CallOption) (*QueryHoldTokenResponse, error) {
	client := trade.NewTradeClient(m.cli.Conn())
	return client.QueryHoldingToken(ctx, in, opts...)
}

func (m *defaultTrade) GetGasInfo(ctx context.Context, in *GetGasInfoRequest, opts ...grpc.CallOption) (*GetGasInfoResponse, error) {
	client := trade.NewTradeClient(m.cli.Conn())
	return client.GetGasInfo(ctx, in, opts...)
}

func (m *defaultTrade) AddLiquidityV1(ctx context.Context, in *AddLiquidityRequest, opts ...grpc.CallOption) (*AddLiquidityResponse, error) {
	client := trade.NewTradeClient(m.cli.Conn())
	return client.AddLiquidityV1(ctx, in, opts...)
}

func (m *defaultTrade) TestRpc(ctx context.Context, in *TestRpcRequest, opts ...grpc.CallOption) (*TestRpcResponse, error) {
	client := trade.NewTradeClient(m.cli.Conn())
	return client.TestRpc(ctx, in, opts...)
}

// internal
func (m *defaultTrade) Transfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error) {
	client := trade.NewTradeClient(m.cli.Conn())
	return client.Transfer(ctx, in, opts...)
}

func (m *defaultTrade) QueryTransfer(ctx context.Context, in *QueryTransferRequest, opts ...grpc.CallOption) (*QueryTransferResponse, error) {
	client := trade.NewTradeClient(m.cli.Conn())
	return client.QueryTransfer(ctx, in, opts...)
}
