// Code generated by goctl. DO NOT EDIT!

package solmodel

import (
	"context"
	"database/sql"
	"strings"
	"time"

	"github.com/klen-ygs/gorm-zero/gormc"
	. "github.com/klen-ygs/gorm-zero/gormc/sql"
	"gorm.io/gorm"
)

// avoid unused err
var _ = time.Second

type (
	clmmPoolInfoV1Model interface {
		Insert(ctx context.Context, data *ClmmPoolInfoV1) error

		FindOne(ctx context.Context, id int64) (*ClmmPoolInfoV1, error)
		FindOneByPoolState(ctx context.Context, poolState string) (*ClmmPoolInfoV1, error)
		Update(ctx context.Context, data *ClmmPoolInfoV1) error

		Delete(ctx context.Context, id int64) error
	}

	defaultClmmPoolInfoV1Model struct {
		conn  *gorm.DB
		table string
	}

	ClmmPoolInfoV1 struct {
		Id                int64        `gorm:"column:id"`                 // Primary Key
		AmmConfig         string       `gorm:"column:amm_config"`         // AMM Pool Configuration
		PoolState         string       `gorm:"column:pool_state"`         // AMM Pool State Account
		InputVault        string       `gorm:"column:input_vault"`        // Input Token Vault
		TickArray         string       `gorm:"column:tick_array"`         // Tick Array
		OutputVault       string       `gorm:"column:output_vault"`       // Output Token Vault
		ObservationState  string       `gorm:"column:observation_state"`  // Oracle Observation State
		TokenProgram      string       `gorm:"column:token_program"`      // SPL Token Program
		TokenProgram2022  string       `gorm:"column:token_program_2022"` // SPL Token Program 2022
		MemoProgram       string       `gorm:"column:memo_program"`       // Transaction Memo Program (Optional)
		InputVaultMint    string       `gorm:"column:input_vault_mint"`   // Input Vault Mint
		OutputVaultMint   string       `gorm:"column:output_vault_mint"`  // Output Vault Mint
		RemainingAccounts string       `gorm:"column:remaining_accounts"` // Remaining Accounts (JSON format)
		TradeFeeRate      int64        `gorm:"column:trade_fee_rate"`     // Trade Fee Rate
		TxHash            string       `gorm:"column:tx_hash"`            // Tx hash
		CreatedAt         time.Time    `gorm:"column:created_at"`         // Creation timestamp
		UpdatedAt         time.Time    `gorm:"column:updated_at"`         // Update timestamp
		DeletedAt         sql.NullTime `gorm:"column:deleted_at;index"`   // Soft delete timestamp
	}
)

var QClmmPoolInfoV1 ClmmPoolInfoV1

func init() {
	InitField(&QClmmPoolInfoV1)
}

func (ClmmPoolInfoV1) TableName() string {
	return strings.Trim("`clmm_pool_info_v1`", "`")
}

func newClmmPoolInfoV1Model(conn *gorm.DB) *defaultClmmPoolInfoV1Model {
	return &defaultClmmPoolInfoV1Model{
		conn:  conn,
		table: strings.Trim("`clmm_pool_info_v1`", "`"),
	}
}

func (m *defaultClmmPoolInfoV1Model) Insert(ctx context.Context, data *ClmmPoolInfoV1) error {
	db := m.conn
	err := db.WithContext(ctx).Save(&data).Error
	return err
}

func (m *defaultClmmPoolInfoV1Model) FindOne(ctx context.Context, id int64) (*ClmmPoolInfoV1, error) {
	var resp ClmmPoolInfoV1
	err := m.conn.WithContext(ctx).Model(&ClmmPoolInfoV1{}).Where("`id` = @id", sql.Named("id", id)).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err

}

func (m *defaultClmmPoolInfoV1Model) FindOneByPoolState(ctx context.Context, poolState string) (*ClmmPoolInfoV1, error) {
	var resp ClmmPoolInfoV1
	err := m.conn.WithContext(ctx).Model(&ClmmPoolInfoV1{}).Where("`pool_state` = ?", poolState).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err
}

func (m *defaultClmmPoolInfoV1Model) Update(ctx context.Context, data *ClmmPoolInfoV1) error {
	db := m.conn
	err := db.WithContext(ctx).Save(data).Error
	return err
}

func (m *defaultClmmPoolInfoV1Model) Delete(ctx context.Context, id int64) error {
	db := m.conn
	err := db.WithContext(ctx).Where("`id` = @id", sql.Named("id", id)).Delete(&ClmmPoolInfoV1{}).Error

	return err
}
