// Code generated by goctl. DO NOT EDIT!

package solmodel

import (
	"context"
	"database/sql"
	"strings"
	"time"

	"github.com/klen-ygs/gorm-zero/gormc"
	. "github.com/klen-ygs/gorm-zero/gormc/sql"
	"gorm.io/gorm"
)

// avoid unused err
var _ = time.Second

type (
	cpmmPoolInfoModel interface {
		Insert(ctx context.Context, data *CpmmPoolInfo) error

		FindOne(ctx context.Context, id int64) (*CpmmPoolInfo, error)
		FindOneByPoolState(ctx context.Context, poolState string) (*CpmmPoolInfo, error)
		Update(ctx context.Context, data *CpmmPoolInfo) error

		Delete(ctx context.Context, id int64) error
	}

	defaultCpmmPoolInfoModel struct {
		conn  *gorm.DB
		table string
	}

	CpmmPoolInfo struct {
		Id                 int64     `gorm:"column:id"`                   // Primary Key
		AmmConfig          string    `gorm:"column:amm_config"`           // AMM Config Account
		PoolState          string    `gorm:"column:pool_state"`           // Pool State Account
		InputVault         string    `gorm:"column:input_vault"`          // Input Vault
		Authority          string    `gorm:"column:authority"`            // Authority
		OutputVault        string    `gorm:"column:output_vault"`         // Output Vault
		InputTokenProgram  string    `gorm:"column:input_token_program"`  // Input Token Program
		OutputTokenProgram string    `gorm:"column:output_token_program"` // Output Token Program
		InputTokenMint     string    `gorm:"column:input_token_mint"`     // Input Token Mint
		OutputTokenMint    string    `gorm:"column:output_token_mint"`    // Output Token Mint
		TradeFeeRate       int64     `gorm:"column:trade_fee_rate"`       // Trade Fee Rate
		ObservationState   string    `gorm:"column:observation_state"`    // Observation State
		TxHash             string    `gorm:"column:tx_hash"`              // Tx hash
		CreatedAt          time.Time `gorm:"column:created_at"`           // Creation timestamp
		UpdatedAt          time.Time `gorm:"column:updated_at"`           // Update timestamp
	}
)

var QCpmmPoolInfo CpmmPoolInfo

func init() {
	InitField(&QCpmmPoolInfo)
}

func (CpmmPoolInfo) TableName() string {
	return strings.Trim("`cpmm_pool_info`", "`")
}

func newCpmmPoolInfoModel(conn *gorm.DB) *defaultCpmmPoolInfoModel {
	return &defaultCpmmPoolInfoModel{
		conn:  conn,
		table: strings.Trim("`cpmm_pool_info`", "`"),
	}
}

func (m *defaultCpmmPoolInfoModel) Insert(ctx context.Context, data *CpmmPoolInfo) error {
	db := m.conn
	err := db.WithContext(ctx).Save(&data).Error
	return err
}

func (m *defaultCpmmPoolInfoModel) FindOne(ctx context.Context, id int64) (*CpmmPoolInfo, error) {
	var resp CpmmPoolInfo
	err := m.conn.WithContext(ctx).Model(&CpmmPoolInfo{}).Where("`id` = @id", sql.Named("id", id)).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err

}

func (m *defaultCpmmPoolInfoModel) FindOneByPoolState(ctx context.Context, poolState string) (*CpmmPoolInfo, error) {
	var resp CpmmPoolInfo
	err := m.conn.WithContext(ctx).Model(&CpmmPoolInfo{}).Where("`pool_state` = ?", poolState).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err
}

func (m *defaultCpmmPoolInfoModel) Update(ctx context.Context, data *CpmmPoolInfo) error {
	db := m.conn
	err := db.WithContext(ctx).Save(data).Error
	return err
}

func (m *defaultCpmmPoolInfoModel) Delete(ctx context.Context, id int64) error {
	db := m.conn
	err := db.WithContext(ctx).Where("`id` = @id", sql.Named("id", id)).Delete(&CpmmPoolInfo{}).Error

	return err
}
