// Code generated by goctl. DO NOT EDIT!

package solmodel

import (
	"context"
	"database/sql"
	"strings"
	"time"

	"github.com/klen-ygs/gorm-zero/gormc"
	. "github.com/klen-ygs/gorm-zero/gormc/sql"
	"gorm.io/gorm"
)

// avoid unused err
var _ = time.Second

type (
	pumpAmmInfoModel interface {
		Insert(ctx context.Context, data *PumpAmmInfo) error

		FindOne(ctx context.Context, id int64) (*PumpAmmInfo, error)
		FindOneByPoolAccount(ctx context.Context, poolAccount string) (*PumpAmmInfo, error)
		Update(ctx context.Context, data *PumpAmmInfo) error

		Delete(ctx context.Context, id int64) error
	}

	defaultPumpAmmInfoModel struct {
		conn  *gorm.DB
		table string
	}

	PumpAmmInfo struct {
		Id                               int64        `gorm:"column:id"`                                   // Primary Key
		PoolAccount                      string       `gorm:"column:pool_account"`                         // Pool account address
		GlobalConfigAccount              string       `gorm:"column:global_config_account"`                // Global configuration account address
		BaseMintAccount                  string       `gorm:"column:base_mint_account"`                    // Base mint address
		QuoteMintAccount                 string       `gorm:"column:quote_mint_account"`                   // Quote mint address
		PoolBaseTokenAccount             string       `gorm:"column:pool_base_token_account"`              // Pool''s base token account
		PoolQuoteTokenAccount            string       `gorm:"column:pool_quote_token_account"`             // Pool''s quote token account
		ProtocolFeeRecipientAccount      string       `gorm:"column:protocol_fee_recipient_account"`       // Protocol fee recipient account
		ProtocolFeeRecipientTokenAccount string       `gorm:"column:protocol_fee_recipient_token_account"` // Protocol fee recipient token account
		BaseTokenProgram                 string       `gorm:"column:base_token_program"`                   // Base token program address
		QuoteTokenProgram                string       `gorm:"column:quote_token_program"`                  // Quote token program address
		SystemProgram                    string       `gorm:"column:system_program"`                       // System program address
		AssociatedTokenProgram           string       `gorm:"column:associated_token_program"`             // Associated token program address
		EventAuthorityAccount            string       `gorm:"column:event_authority_account"`              // Event authority account
		ProgramAccount                   string       `gorm:"column:program_account"`                      // Program account address
		CoinCreatorVaultAuthority        string       `gorm:"column:coin_creator_vault_authority"`         // Coin creator vault authority address
		CoinCreatorVaultAta              string       `gorm:"column:coin_creator_vault_ata"`               // Coin creator vault ATA address
		CreatedAt                        time.Time    `gorm:"column:created_at"`                           // Creation timestamp
		UpdatedAt                        time.Time    `gorm:"column:updated_at"`                           // Update timestamp
		DeletedAt                        sql.NullTime `gorm:"column:deleted_at;index"`                     // Soft delete timestamp
	}
)

var QPumpAmmInfo PumpAmmInfo

func init() {
	InitField(&QPumpAmmInfo)
}

func (PumpAmmInfo) TableName() string {
	return strings.Trim("`pump_amm_info`", "`")
}

func newPumpAmmInfoModel(conn *gorm.DB) *defaultPumpAmmInfoModel {
	return &defaultPumpAmmInfoModel{
		conn:  conn,
		table: strings.Trim("`pump_amm_info`", "`"),
	}
}

func (m *defaultPumpAmmInfoModel) Insert(ctx context.Context, data *PumpAmmInfo) error {
	db := m.conn
	err := db.WithContext(ctx).Save(&data).Error
	return err
}

func (m *defaultPumpAmmInfoModel) FindOne(ctx context.Context, id int64) (*PumpAmmInfo, error) {
	var resp PumpAmmInfo
	err := m.conn.WithContext(ctx).Model(&PumpAmmInfo{}).Where("`id` = @id", sql.Named("id", id)).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err

}

func (m *defaultPumpAmmInfoModel) FindOneByPoolAccount(ctx context.Context, poolAccount string) (*PumpAmmInfo, error) {
	var resp PumpAmmInfo
	err := m.conn.WithContext(ctx).Model(&PumpAmmInfo{}).Where("`pool_account` = ?", poolAccount).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err
}

func (m *defaultPumpAmmInfoModel) Update(ctx context.Context, data *PumpAmmInfo) error {
	db := m.conn
	err := db.WithContext(ctx).Save(data).Error
	return err
}

func (m *defaultPumpAmmInfoModel) Delete(ctx context.Context, id int64) error {
	db := m.conn
	err := db.WithContext(ctx).Where("`id` = @id", sql.Named("id", id)).Delete(&PumpAmmInfo{}).Error

	return err
}
