// Code generated by goctl. DO NOT EDIT!

package solmodel

import (
	"context"
	"database/sql"
	"strings"
	"time"

	"github.com/klen-ygs/gorm-zero/gormc"
	. "github.com/klen-ygs/gorm-zero/gormc/sql"
	"gorm.io/gorm"
)

// avoid unused err
var _ = time.Second

type (
	raydiumPoolModel interface {
		Insert(ctx context.Context, data *RaydiumPool) error

		FindOne(ctx context.Context, id int64) (*RaydiumPool, error)
		FindOneByChainIdAmmId(ctx context.Context, chainId int64, ammId string) (*RaydiumPool, error)
		Update(ctx context.Context, data *RaydiumPool) error

		Delete(ctx context.Context, id int64) error
	}

	defaultRaydiumPoolModel struct {
		conn  *gorm.DB
		table string
	}

	RaydiumPool struct {
		Id                    int64        `gorm:"column:id"`
		ChainId               int64        `gorm:"column:chain_id"`                 // Chain ID
		AmmId                 string       `gorm:"column:amm_id"`                   // AMM ID (pair address)
		AmmAuthority          string       `gorm:"column:amm_authority"`            // AMM Authority
		AmmOpenOrders         string       `gorm:"column:amm_open_orders"`          // AMM Open Orders
		AmmTargetOrders       string       `gorm:"column:amm_target_orders"`        // AMM Target Orders
		PoolCoinTokenAccount  string       `gorm:"column:pool_coin_token_account"`  // Pool Coin Token Account
		PoolPcTokenAccount    string       `gorm:"column:pool_pc_token_account"`    // Pool PC Token Account
		SerumProgramId        string       `gorm:"column:serum_program_id"`         // Serum Program ID
		SerumMarket           string       `gorm:"column:serum_market"`             // Serum Market
		SerumBids             string       `gorm:"column:serum_bids"`               // Serum Bids
		SerumAsks             string       `gorm:"column:serum_asks"`               // Serum Asks
		SerumEventQueue       string       `gorm:"column:serum_event_queue"`        // Serum Event Queue
		SerumCoinVaultAccount string       `gorm:"column:serum_coin_vault_account"` // Serum Coin Vault Account
		SerumPcVaultAccount   string       `gorm:"column:serum_pc_vault_account"`   // Serum PC Vault Account
		SerumVaultSigner      string       `gorm:"column:serum_vault_signer"`       // Serum Vault Signer
		CreatedAt             time.Time    `gorm:"column:created_at"`               // Creation timestamp
		UpdatedAt             time.Time    `gorm:"column:updated_at"`               // Update timestamp
		DeletedAt             sql.NullTime `gorm:"column:deleted_at;index"`
		TxHash                string       `gorm:"column:tx_hash"`
		BaseMint              string       `gorm:"column:base_mint"`
		QuoteMint             string       `gorm:"column:quote_mint"`
	}
)

var QRaydiumPool RaydiumPool

func init() {
	InitField(&QRaydiumPool)
}

func (RaydiumPool) TableName() string {
	return strings.Trim("`raydium_pool`", "`")
}

func newRaydiumPoolModel(conn *gorm.DB) *defaultRaydiumPoolModel {
	return &defaultRaydiumPoolModel{
		conn:  conn,
		table: strings.Trim("`raydium_pool`", "`"),
	}
}

func (m *defaultRaydiumPoolModel) Insert(ctx context.Context, data *RaydiumPool) error {
	db := m.conn
	err := db.WithContext(ctx).Save(&data).Error
	return err
}

func (m *defaultRaydiumPoolModel) FindOne(ctx context.Context, id int64) (*RaydiumPool, error) {
	var resp RaydiumPool
	err := m.conn.WithContext(ctx).Model(&RaydiumPool{}).Where("`id` = @id", sql.Named("id", id)).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err

}

func (m *defaultRaydiumPoolModel) FindOneByChainIdAmmId(ctx context.Context, chainId int64, ammId string) (*RaydiumPool, error) {
	var resp RaydiumPool
	err := m.conn.WithContext(ctx).Model(&RaydiumPool{}).Where("`chain_id` = ? and `amm_id` = ?", chainId, ammId).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err
}

func (m *defaultRaydiumPoolModel) Update(ctx context.Context, data *RaydiumPool) error {
	db := m.conn
	err := db.WithContext(ctx).Save(data).Error
	return err
}

func (m *defaultRaydiumPoolModel) Delete(ctx context.Context, id int64) error {
	db := m.conn
	err := db.WithContext(ctx).Where("`id` = @id", sql.Named("id", id)).Delete(&RaydiumPool{}).Error

	return err
}
