// Code generated by goctl. DO NOT EDIT!

package solmodel

import (
	"context"
	"database/sql"
	"strings"
	"time"

	"github.com/klen-ygs/gorm-zero/gormc"
	. "github.com/klen-ygs/gorm-zero/gormc/sql"
	"gorm.io/gorm"
)

// avoid unused err
var _ = time.Second

type (
	userTokensModel interface {
		Insert(ctx context.Context, data *UserTokens) error

		FindOne(ctx context.Context, id int64) (*UserTokens, error)
		FindOneByUserWalletAddressTokenAddress(ctx context.Context, userWalletAddress string, tokenAddress string) (*UserTokens, error)
		Update(ctx context.Context, data *UserTokens) error

		Delete(ctx context.Context, id int64) error
	}

	defaultUserTokensModel struct {
		conn  *gorm.DB
		table string
	}

	UserTokens struct {
		Id                int64        `gorm:"column:id"`
		UserWalletAddress string       `gorm:"column:user_wallet_address"` // User wallet address
		ChainId           int64        `gorm:"column:chain_id"`            // Chain ID
		TokenAddress      string       `gorm:"column:token_address"`       // Token contract address
		TokenProgram      string       `gorm:"column:token_program"`       // Token program ID
		Name              string       `gorm:"column:name"`                // Token name
		Symbol            string       `gorm:"column:symbol"`              // Token symbol
		Decimals          int64        `gorm:"column:decimals"`            // Token decimals
		TotalSupply       float64      `gorm:"column:total_supply"`        // Total token supply
		Icon              string       `gorm:"column:icon"`                // Token icon URL
		Description       string       `gorm:"column:description"`         // Token description
		TxHash            string       `gorm:"column:tx_hash"`             // Creation transaction hash
		CreatedAt         time.Time    `gorm:"column:created_at"`          // Creation timestamp
		UpdatedAt         time.Time    `gorm:"column:updated_at"`          // Update timestamp
		DeletedAt         sql.NullTime `gorm:"column:deleted_at;index"`    // Soft delete timestamp
	}
)

var QUserTokens UserTokens

func init() {
	InitField(&QUserTokens)
}

func (UserTokens) TableName() string {
	return strings.Trim("`user_tokens`", "`")
}

func newUserTokensModel(conn *gorm.DB) *defaultUserTokensModel {
	return &defaultUserTokensModel{
		conn:  conn,
		table: strings.Trim("`user_tokens`", "`"),
	}
}

func (m *defaultUserTokensModel) Insert(ctx context.Context, data *UserTokens) error {
	db := m.conn
	err := db.WithContext(ctx).Save(&data).Error
	return err
}

func (m *defaultUserTokensModel) FindOne(ctx context.Context, id int64) (*UserTokens, error) {
	var resp UserTokens
	err := m.conn.WithContext(ctx).Model(&UserTokens{}).Where("`id` = @id", sql.Named("id", id)).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err

}

func (m *defaultUserTokensModel) FindOneByUserWalletAddressTokenAddress(ctx context.Context, userWalletAddress string, tokenAddress string) (*UserTokens, error) {
	var resp UserTokens
	err := m.conn.WithContext(ctx).Model(&UserTokens{}).Where("`user_wallet_address` = ? and `token_address` = ?", userWalletAddress, tokenAddress).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err
}

func (m *defaultUserTokensModel) Update(ctx context.Context, data *UserTokens) error {
	db := m.conn
	err := db.WithContext(ctx).Save(data).Error
	return err
}

func (m *defaultUserTokensModel) Delete(ctx context.Context, id int64) error {
	db := m.conn
	err := db.WithContext(ctx).Where("`id` = @id", sql.Named("id", id)).Delete(&UserTokens{}).Error

	return err
}
