// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: trade.proto

package server

import (
	"context"

	"dex/trade/internal/logic"
	"dex/trade/internal/svc"
	"dex/trade/trade"
)

type TradeServer struct {
	svcCtx *svc.ServiceContext
	trade.UnimplementedTradeServer
}

func NewTradeServer(svcCtx *svc.ServiceContext) *TradeServer {
	return &TradeServer{
		svcCtx: svcCtx,
	}
}

func (s *TradeServer) CreateLimitOrder(ctx context.Context, in *trade.CreateLimitOrderRequest) (*trade.CreateLimitOrderResponse, error) {
	l := logic.NewCreateLimitOrderLogic(ctx, s.svcCtx)
	return l.CreateLimitOrder(in)
}

func (s *TradeServer) CancelOrder(ctx context.Context, in *trade.CancelOrderRequest) (*trade.CancelOrderResponse, error) {
	l := logic.NewCancelOrderLogic(ctx, s.svcCtx)
	return l.CancelOrder(in)
}

func (s *TradeServer) CreateMarketOrder(ctx context.Context, in *trade.CreateMarketOrderRequest) (*trade.CreateMarketOrderResponse, error) {
	l := logic.NewCreateMarketOrderLogic(ctx, s.svcCtx)
	return l.CreateMarketOrder(in)
}

func (s *TradeServer) CreatePool(ctx context.Context, in *trade.CreatePoolRequest) (*trade.CreatePoolResponse, error) {
	l := logic.NewCreatePoolLogic(ctx, s.svcCtx)
	return l.CreatePool(in)
}

func (s *TradeServer) QueryCurrentOrders(ctx context.Context, in *trade.QueryCurrentOrdersRequest) (*trade.QueryCurrentOrdersResponse, error) {
	l := logic.NewQueryCurrentOrdersLogic(ctx, s.svcCtx)
	return l.QueryCurrentOrders(in)
}

func (s *TradeServer) QueryTradeHistory(ctx context.Context, in *trade.QueryTradeHistoryRequest) (*trade.QueryTradeHistoryResponse, error) {
	l := logic.NewQueryTradeHistoryLogic(ctx, s.svcCtx)
	return l.QueryTradeHistory(in)
}

func (s *TradeServer) QueryOrderHistory(ctx context.Context, in *trade.QueryOrderHistoryRequest) (*trade.QueryOrderHistoryResponse, error) {
	l := logic.NewQueryOrderHistoryLogic(ctx, s.svcCtx)
	return l.QueryOrderHistory(in)
}

func (s *TradeServer) ProcTokenPrice(ctx context.Context, in *trade.ProcTokenPriceRequest) (*trade.ProcTokenPriceResponse, error) {
	l := logic.NewProcTokenPriceLogic(ctx, s.svcCtx)
	return l.ProcTokenPrice(in)
}

func (s *TradeServer) ProcTokenCap(ctx context.Context, in *trade.ProcTokenCapRequest) (*trade.ProcTokenCapResponse, error) {
	l := logic.NewProcTokenCapLogic(ctx, s.svcCtx)
	return l.ProcTokenCap(in)
}

func (s *TradeServer) CreateTrailingStop(ctx context.Context, in *trade.CreateTrailingStopRequest) (*trade.CreateTrailingStopResponse, error) {
	l := logic.NewCreateTrailingStopLogic(ctx, s.svcCtx)
	return l.CreateTrailingStop(in)
}

func (s *TradeServer) ProcTrailingStop(ctx context.Context, in *trade.ProcTokenPriceRequest) (*trade.ProcTokenPriceResponse, error) {
	l := logic.NewProcTrailingStopLogic(ctx, s.svcCtx)
	return l.ProcTrailingStop(in)
}

func (s *TradeServer) QueryHoldingToken(ctx context.Context, in *trade.QueryHoldTokenRequest) (*trade.QueryHoldTokenResponse, error) {
	l := logic.NewQueryHoldingTokenLogic(ctx, s.svcCtx)
	return l.QueryHoldingToken(in)
}

func (s *TradeServer) GetGasInfo(ctx context.Context, in *trade.GetGasInfoRequest) (*trade.GetGasInfoResponse, error) {
	l := logic.NewGetGasInfoLogic(ctx, s.svcCtx)
	return l.GetGasInfo(in)
}

func (s *TradeServer) AddLiquidityV1(ctx context.Context, in *trade.AddLiquidityRequest) (*trade.AddLiquidityResponse, error) {
	l := logic.NewAddLiquidityV1Logic(ctx, s.svcCtx)
	return l.AddLiquidityV1(in)
}

func (s *TradeServer) TestRpc(ctx context.Context, in *trade.TestRpcRequest) (*trade.TestRpcResponse, error) {
	l := logic.NewTestRpcLogic(ctx, s.svcCtx)
	return l.TestRpc(in)
}

// internal
func (s *TradeServer) Transfer(ctx context.Context, in *trade.TransferRequest) (*trade.TransferResponse, error) {
	l := logic.NewTransferLogic(ctx, s.svcCtx)
	return l.Transfer(in)
}

func (s *TradeServer) QueryTransfer(ctx context.Context, in *trade.QueryTransferRequest) (*trade.QueryTransferResponse, error) {
	l := logic.NewQueryTransferLogic(ctx, s.svcCtx)
	return l.QueryTransfer(in)
}
