// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: greet/consumer/consumer.proto

package consumer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ping          string                 `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_greet_consumer_consumer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greet_consumer_consumer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_greet_consumer_consumer_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetPing() string {
	if x != nil {
		return x.Ping
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pong          string                 `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_greet_consumer_consumer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_greet_consumer_consumer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_greet_consumer_consumer_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

var File_greet_consumer_consumer_proto protoreflect.FileDescriptor

const file_greet_consumer_consumer_proto_rawDesc = "" +
	"\n" +
	"\x1dgreet/consumer/consumer.proto\x12\bconsumer\"!\n" +
	"\vPingRequest\x12\x12\n" +
	"\x04ping\x18\x01 \x01(\tR\x04ping\"\"\n" +
	"\fPingResponse\x12\x12\n" +
	"\x04pong\x18\x01 \x01(\tR\x04pong2A\n" +
	"\bConsumer\x125\n" +
	"\x04Ping\x12\x15.consumer.PingRequest\x1a\x16.consumer.PingResponseB\fZ\n" +
	"./consumerb\x06proto3"

var (
	file_greet_consumer_consumer_proto_rawDescOnce sync.Once
	file_greet_consumer_consumer_proto_rawDescData []byte
)

func file_greet_consumer_consumer_proto_rawDescGZIP() []byte {
	file_greet_consumer_consumer_proto_rawDescOnce.Do(func() {
		file_greet_consumer_consumer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_greet_consumer_consumer_proto_rawDesc), len(file_greet_consumer_consumer_proto_rawDesc)))
	})
	return file_greet_consumer_consumer_proto_rawDescData
}

var file_greet_consumer_consumer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_greet_consumer_consumer_proto_goTypes = []any{
	(*PingRequest)(nil),  // 0: consumer.PingRequest
	(*PingResponse)(nil), // 1: consumer.PingResponse
}
var file_greet_consumer_consumer_proto_depIdxs = []int32{
	0, // 0: consumer.Consumer.Ping:input_type -> consumer.PingRequest
	1, // 1: consumer.Consumer.Ping:output_type -> consumer.PingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_greet_consumer_consumer_proto_init() }
func file_greet_consumer_consumer_proto_init() {
	if File_greet_consumer_consumer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_greet_consumer_consumer_proto_rawDesc), len(file_greet_consumer_consumer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_greet_consumer_consumer_proto_goTypes,
		DependencyIndexes: file_greet_consumer_consumer_proto_depIdxs,
		MessageInfos:      file_greet_consumer_consumer_proto_msgTypes,
	}.Build()
	File_greet_consumer_consumer_proto = out.File
	file_greet_consumer_consumer_proto_goTypes = nil
	file_greet_consumer_consumer_proto_depIdxs = nil
}
