// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: dataflow.proto

package dataflowclient

import (
	"dex/dataflow/dataflow"

	"github.com/zeromicro/go-zero/zrpc"
)

type (
	Kline            = dataflow.Kline
	Kline24InfoItem  = dataflow.Kline24InfoItem
	KlineFluctuation = dataflow.KlineFluctuation
	Klines           = dataflow.Klines

	Dataflow interface {
	}

	defaultDataflow struct {
		cli zrpc.Client
	}
)

func NewDataflow(cli zrpc.Client) Dataflow {
	return &defaultDataflow{
		cli: cli,
	}
}
