// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: dataflow.proto

package server

import (
	"dex/dataflow/dataflow"
	"dex/dataflow/internal/svc"
)

type DataflowServer struct {
	svcCtx *svc.ServiceContext
	dataflow.UnimplementedDataflowServer
}

func NewDataflowServer(svcCtx *svc.ServiceContext) *DataflowServer {
	return &DataflowServer{
		svcCtx: svcCtx,
	}
}
